first_name = '#firstname'
last_name = '#lastname'
email = '#email_address'
password = '#password'
pass_confirm = '#password-confirmation'
submit = '//button[@class="action submit primary"]'
email_error = '#email_address-error'
first_name_error = '#firstname-error'
password_error = '#password-error'
